[package]
name = "framehop"
version = "0.1.0"
edition = "2021"
authors = ["Markus Stange <mstange.moz@gmail.com>"]
categories = ["development-tools::debugging"]
description = "Stack frame unwinding support for various formats"
keywords = ["unwind", "stackwalk", "profiling", "debug"]
license = "MIT/Apache-2.0"
readme = "Readme.md"
exclude = ["/.github", "/.vscode", "/tests", "/fixtures", "/big-fixtures"]

[dependencies]
gimli = "0.26.1"
thiserror = "1.0.30"
macho-unwind-info = "0.3.0"
fallible-iterator = "0.2.0"

[dev-dependencies]
object = "0.28.2"

[profile.release]
debug = true
