[package]
name = "framehop"
version = "0.1.0"
edition = "2021"
authors = ["Markus Stange <mstange.moz@gmail.com>"]
categories = ["development-tools::debugging"]
description = "Rust unwinding library"
keywords = ["unwind", "stackwalk", "profiling", "debug"]
license = "MIT/Apache-2.0"
readme = "Readme.md"
exclude = ["/.github", "/tests", "/res"]

[dependencies]
thiserror = "1.0.30"
zerocopy = "0.6.1"

[dev-dependencies]
object = "0.28.2"

[profile.release]
debug = true
