[package]
name = "rul"
version = "0.1.0"
edition = "2021"
authors = ["Markus Stange <mstange.moz@gmail.com>"]
categories = ["development-tools::debugging"]
description = "Rust unwinding library"
keywords = ["unwind", "stackwalk", "profiling", "debug"]
license = "MIT/Apache-2.0"
readme = "Readme.md"
exclude = ["/.github", "/tests", "/res"]

[dependencies]
